name: Compilation Check

on:
  push:
    branches:
      - '**'

jobs:
  build-linux:
    runs-on:
      - ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Build project
      run: make

  build-Mac:
    runs-on:
      - macos-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Build project
      run: make
